import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li><Link href="/users">Usuarios</Link></li>  
            <li><Link href="/sobre">Sobre</Link></li>  
            <li><Link href="/contato">Contate-me</Link></li>  
          </ul>
        </nav>
        {children}</body>
    </html>
  );
}
